### ISSUE TITLE
Index.js

### ISSUE THREAD

**Issue by RobinNosheen** [justNoOneHere/BTC_PKDir#1]
I think index.js file is missing in this folder.

**Comment by justNoOneHere** [comment]
You can run the script if you install nodejs and install the libraries used in the script
After that just use powershell and go to the folder you saved BTC_PKDir.js
Run the code node BTC_PKDir.js

**Comment by RobinNosheen** [comment]
I install all the libraries also have node.js but after running node BTC_PKDir.js this error is showing. Error: Cannot find module 'prompts'

**Comment by justNoOneHere** [comment]
You didn't install the libraries.

Run this to install all libraries :
npm install crypto bs58 elliptic axios bignumber.js fs https prompts

**Comment by RobinNosheen** [comment]
Thank You i think promts is missing but after installing now it'w working.

**Comment by justNoOneHere** [comment]
If you have any problems or suggestions feel free to say :)
